server:
  port: 8082

info:
  app:
    description: "Notification Service - Consumo de eventos e disparos via MQTT/Push"

spring:
  application:
    name: notification-service

  main:
    banner-mode: "console"
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:notifications_db}
      auto-index-creation: true
      uuid-representation: standard

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 5

iam:
  jwt-secret: ${JWT_SECRET:M2I3YzA5OGU1YmFhN2U3Zjk0ZWY0ZGIyYmU5ZDBjZjkxZWRhYmFmNjA4MGY1ZDIzM2M4ZGM0ZTI5N2I0YmU3YQ==}

mqtt:
  broker-url: tcp://${SPRING_MQTT_HOST:localhost}:1883
  client-id: notification-service-client
  topic: notificacoes/geral

logging:
  level:
    root: INFO
    com.br.order_service: DEBUG
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  endpoint:
    health:
      show-details: always